---
dependencies:
  - { role: "azavea.mapnik" }
  - { role: "azavea.build-essential" }
  - { role: "azavea.swapfile", when: "['development', 'test'] | some_are_in(group_names)" }
  - { role: "nyc-trees.monitoring", collectd_prefix: "collectd.tile.", when: "['test'] | is_not_in(group_names)" }
