---
dependencies:
  - { role: "azavea.mapnik" }
  - { role: "azavea.build-essential" }
  - { role: "azavea.swapfile", when: developing_or_testing }
  - { role: "nyc-trees.monitoring", collectd_prefix: "collectd.tile.", when: not_testing }
