---
app_home: /opt/app
app_config_home: /etc/nyc-trees.d/env
app_config:
  - { file: "NYC_TREES_DB_NAME", content: "{{ postgresql_database }}" }
  - { file: "NYC_TREES_DB_USER", content: "{{ postgresql_username }}" }
  - { file: "NYC_TREES_DB_PASSWORD", content: "{{ postgresql_password }}" }
  - { file: "NYC_TREES_DB_HOST", content: "{{ postgresql_host }}" }
  - { file: "NYC_TREES_DB_PORT", content: "{{ postgresql_port }}" }
