---
dependencies:
  - { role: "azavea.ntp" }
  - { role: "azavea.git" }
  - { role: "azavea.nginx", nginx_delete_default_site: True, when: "['monitoring-servers'] | is_not_in(group_names)" }
  - { role: "azavea.daemontools", when: "['monitoring-servers'] | is_not_in(group_names)" }
  - { role: "azavea.nodejs", when: "['monitoring-servers'] | is_not_in(group_names)" }
