---
- name: Touch log file if it does not exist
  command: touch {{ tiler_log }}
           creates={{ tiler_log }}

- name: Set log file permissions
  file: path={{ tiler_log }} owner=nyc-trees group=nyc-trees mode=0644

- name: Configure Tiler log rotation
  template: src=logrotate-nyc-trees-tiler.j2 dest=/etc/logrotate.d/nyc-trees-tiler
