---
- name: Install Geospatial libraries
  apt: pkg={{ item }} state=present
  with_items:
    - binutils=2.24-5ubuntu3
    - libproj-dev=4.8.0-2ubuntu2
    - gdal-bin=1.10.1+dfsg-5ubuntu1

- name: Install PostgreSQL client
  apt: pkg=postgresql-client-{{ postgresql_version }}={{ postgresql_package_version }}

- name: Install application python dependencies for development and test
  pip: chdir={{ app_home }}/requirements requirements={{ item }}.txt
  with_items:
    - development
    - test
  when: developing_or_testing

- name: Install Firefox and Xvfb for headless UI tests
  apt: pkg={{ item }} state=present
  with_items:
      - firefox=33.0+build2-0ubuntu0.14.04.1
  when: developing_or_testing
