---
- name: Install Geospatial libraries
  apt: pkg={{ item }} state=present
  with_items:
    - binutils=2.24-5ubuntu3
    - libproj-dev=4.8.0-2ubuntu2
    - gdal-bin=1.10.1+dfsg-5ubuntu1

- name: Configure the main PostgreSQL APT repository
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release}}-pgdg main"
                  state=present

- name: Install PostgreSQL client
  apt: pkg=postgresql-client-{{ postgresql_version }}={{ postgresql_package_version }}

- name: Install application Python dependencies for production
  pip: chdir="{{ app_home }}/requirements" requirements=production.txt
  when: packing
  notify:
    - Restart nyc-trees-app

- name: Download Sauce Connect for UI tests
  get_url: url={{ sauce_connect_url }} dest={{ sauce_connect_archive }}
  when: sauce_labs_api_key_is_defined

- name: Extract Sauce Connect for UI tests
  unarchive:
    src={{ sauce_connect_archive }}
    copy=no
    dest={{ sauce_connect_archive_dir }}
    creates={{ sauce_connect_dir }}
  when: sauce_labs_api_key_is_defined
