---
- name: Install Geospatial libraries
  apt: pkg={{ item }} state=present
  with_items:
    - "binutils=2.24*"
    - "libproj-dev=4.8.0*"
    - "gdal-bin=1.10.1*"

- name: Configure the main PostgreSQL APT repository
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release}}-pgdg main"
                  state=present

- name: Install PostgreSQL client
  apt: pkg=postgresql-client-{{ postgresql_version }}={{ postgresql_package_version }}

- name: Install python-cairo (for PDF generation)
  apt: pkg=python-cairo=1.8.8-1ubuntu5 state=present

- name: Install application Python dependencies for production
  pip: chdir="{{ app_home }}/requirements" requirements=production.txt
  when: "['packer'] | is_in(group_names)"
  notify:
    - Restart nyc-trees-app
