---
- { include: configuration.yml }
- { include: app.yml }
- { include: dependencies.yml }
- { include: dev-and-test-dependencies.yml, when: developing_or_testing }
- { include: static-files.yml }
- { include: reverse-proxy.yml }
- { include: log-rotation.yml }
