---
- name: Create folders for static files
  file: path={{ item }}
        state=directory
        owner=root
        group=nyc-trees
        mode=0775
  with_items:
    - "{{ app_static_root }}"
    - "{{ app_media_root }}"
    - "{{ app_static_cache }}"

- name: Install Sass
  gem: name=sass
       version=3.4.9
       user_install=no
       state=present

- name: Install application javascript dependencies
  command: npm install
  args:
    chdir: "{{ app_home }}"

- name: Create static files and run collectstatic (staging/production)
  command: npm run build
  args:
    chdir: "{{ app_home }}"
  when: not_developing

- name: Create static files and run collectstatic (development)
  command: npm run build-debug
  args:
    chdir: "{{ app_home }}"
  when: developing

- name: Create JS test harness
  template: src=testem-harness.html.j2
            dest={{ app_static_root }}/test.html
  sudo_user: nyc-trees
  when: developing_or_testing
