---
- hosts: app-servers
  sudo: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "nyc-trees.common" }
    - { role: "nyc-trees.collectd" }
    - { role: "nyc-trees.app" }
