---
- hosts: services
  sudo: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "nyc-trees.common" }
    - { role: "nyc-trees.postgresql", when: "'development' in group_names" }

    - { role: "azavea.redis", when: "'development' in group_names" }
    - { role: "azavea.kibana" }
    - { role: "nyc-trees.logstash" }
    - { role: "nyc-trees.graphite" }
