---
- hosts: services
  sudo: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "nyc-trees.common" }

    - { role: "nyc-trees.postgresql", when: developing_or_testing }
    - { role: "nyc-trees.pgweb", when: developing_or_testing }
    - { role: "azavea.redis", when: developing_or_testing }

- hosts: monitoring-servers
  sudo: True

  roles:
    # Keep nyc-trees.graphite ahead of nyc-trees.logstash because the
    # apache2 package clobbers whatever exists in /var/www/html
    - { role: "nyc-trees.graphite", when: not_testing }
    - { role: "azavea.kibana", when: not_testing }
    - { role: "nyc-trees.logstash", when: not_testing }
