---
- hosts: tile-servers
  sudo: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - { role: "nyc-trees.common" }
    - { role: "nyc-trees.monitoring", when: not_testing }

    - { role: "azavea.nodejs" }
    - { role: "azavea.mapnik" }
